### ISSUE TITLE
Burp complains about a missing "jwt library"

### ISSUE THREAD

**Issue by Os3r3um** [pinnace/burp-jwt-fuzzhelper-extension#3]
Hi, 

Thanks for your work. I got a try of this one and I get an error message while trying to load with burp:

```
Traceback (most recent call last):
  File "/root/Desktop/burp_suite/burp-jwt-fuzzhelper-extension/burp-jwt-fuzzhelper.py", line 36, in <module>
    import jwt
ImportError: No module named jwt

	at org.python.core.Py.ImportError(Py.java:328)
	at org.python.core.imp.import_first(imp.java:877)
	at org.python.core.imp.import_module_level(imp.java:972)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1081)
	at org.python.pycode._pyx5.f$0(/root/Desktop/burp_suite/burp-jwt-fuzzhelper-extension/burp-jwt-fuzzhelper.py:546)
	at org.python.pycode._pyx5.call_function(/root/Desktop/burp_suite/burp-jwt-fuzzhelper-extension/burp-jwt-fuzzhelper.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at burp.p9e.<init>(Unknown Source)
	at burp.wi.a(Unknown Source)
	at burp.aif.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

The package is there as  per below: 

```
pip2 freeze | grep PyJWT
PyJWT==1.5.3
```
Any suggestions? 

Regards

**Comment by bdecampe** [comment]
Hi,
Same issue here.
I'm trying to figure it out

Cheers,

**Comment by pinnace** [comment]
@Os3r3um 

No problem, I'll try and replicate this issue in a clean environment and get back to you.

**Comment by pinnace** [comment]
@Os3r3um 

Okay, I've replicated the issue.

First, I've pushed a change to make ImportError's for `jwt` and `rsa` non-fatal.

Second, so for my environment (fully updated Kali + Burp Pro) I have pyjwt in the following location:
`/usr/lib/python2.7/dist-packages/PyJWT-1.5.3.egg-*`. I used `/usr/lib/python2.7/dist-packages/` as my module import path in Burp

my rsa libs were in `/usr/**local**/lib/python2.7/rsa/`, since BurpSuite only accepts one import path I symlinked the libs with `ln -s /usr/local/lib/python2.7/dist-packages/rsa /usr/lib/python2.7/dist-packages/`

Here is my Burp config for Kali:
![screenshot from 2018-04-18 18-50-20](https://user-images.githubusercontent.com/6216202/38949132-704a075a-4339-11e8-856e-2dbb8b427175.png)

Extension successfully loaded
![screenshot from 2018-04-18 18-51-54](https://user-images.githubusercontent.com/6216202/38949263-c9df482a-4339-11e8-9afe-df7e9e5da6fd.png)

Can you confirm whether or not this works for you?

**Comment by pinnace** [comment]
Okay, I figured it out for Kali. Please see the latest comment on the
issue. I'll update the README too. I've also pushed a change to make import
errors non-fatal

**Comment by Os3r3um** [comment]
Thanks for everything. I got it work now. :)

**Comment by NBG0x1** [comment]
![Снимок экрана от 2019-05-19 12-06-55](https://user-images.githubusercontent.com/29577753/57978872-8336c600-7a2e-11e9-87af-59699a05b3d2.png)

**Comment by awesomeaakash** [comment]
I am getting following problem ->

[WARNING] module 'rsa' not found.

`Traceback (most recent call last):
  File "/home/aakash/Desktop/BurpSuite/BurpTools/burp-jwt-fuzzhelper-extension/burp-jwt-fuzzhelper.py", line 51, in <module>
    import pyasn1
ImportError: No module named pyasn1

	at org.python.core.Py.ImportError(Py.java:328)
	at org.python.core.imp.import_first(imp.java:877)
	at org.python.core.imp.import_module_level(imp.java:972)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1081)
	at org.python.pycode._pyx5.f$0(/home/aakash/Desktop/BurpSuite/BurpTools/burp-jwt-fuzzhelper-extension/burp-jwt-fuzzhelper.py:592)
	at org.python.pycode._pyx5.call_function(/home/aakash/Desktop/BurpSuite/BurpTools/burp-jwt-fuzzhelper-extension/burp-jwt-fuzzhelper.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at burp.dgq.<init>(Unknown Source)
	at burp.b8r.a(Unknown Source)
	at burp.ba8.lambda$panelLoaded$0(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
`

sudo pip install -r requirements.txt 
Requirement already satisfied: pyjwt in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1)) (1.7.1)
Requirement already satisfied: rsa in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (3.2.3)

**Comment by pinnace** [comment]
@awesomeaakash 

Hmm, can you show me what your "Folder for Loading Modules" path is in your "Python Environment" setting?

**Comment by awesomeaakash** [comment]
> @awesomeaakash
> 
> Hmm, can you show me what your "Folder for Loading Modules" path is in your "Python Environment" setting?

Yes here it is ->

`python -c "import sys; print sys.path;"
['', '/usr/local/lib/python2.7/dist-packages/JSParser-1.0-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/beautifulsoup4-4.8.0-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/pycurl-7.43.0.3-py2.7-linux-x86_64.egg', '/usr/local/lib/python2.7/dist-packages/netaddr-0.7.19-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/jsbeautifier-1.10.2-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/tornado-6.0.3-py2.7-linux-x86_64.egg', '/usr/local/lib/python2.7/dist-packages/safeurl-0.0.7-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/soupsieve-1.9.4-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/EditorConfig-0.12.2-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/six-1.12.0-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/backports.functools_lru_cache-1.5-py2.7.egg', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/python2.7/dist-packages/wx-3.0-gtk2']
`

**Comment by awesomeaakash** [comment]
And this ->

`python3 -c "import sys; print(sys.path);"
['', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-x86_64-linux-gnu', '/usr/lib/python3.5/lib-dynload', '/usr/local/lib/python3.5/dist-packages', '/usr/lib/python3/dist-packages']

**Comment by pinnace** [comment]
@awesomeaakash can you show me what you have configured for Burp?

e.g.
![image](https://user-images.githubusercontent.com/6216202/66219502-955a8d80-e6cb-11e9-85e0-eaa4bac96d5f.png)

**Comment by awesomeaakash** [comment]
Here it is
/snap/core18/1144/usr/lib/python3/dist-packages

**Comment by pinnace** [comment]
Gotcha. Well that looks alright. And you have pyasn1 installed, correct? 

Also, just noticed that what you provided before is for your python 3 environment
> sudo pip install -r requirements.txt
> Requirement already satisfied: pyjwt in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1)) (1.7.1)
> Requirement already satisfied: rsa in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (3.2.3)

Can you confirm these libraries are present in the python2.7 directory as well?

**Comment by awesomeaakash** [comment]
`ls /usr/lib/python2.7/dist-packages/ -la | grep rsa
lrwxrwxrwx   1 root root     42 Oct  2 12:35 rsa -> /usr/local/lib/python2.7/dist-packages/rsa
`

But no pyjwt in python2.7 even used commmand `sudo pip install pyjwt` but its always install in python3.5

**Comment by pinnace** [comment]
Try `python2 -m pip pyjwt`
